name: run-tests

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
    paths:
      - '**.php'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.php'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-tests"
  run-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: dom, curl, libxml, mbstring
          coverage: none

      - uses: php-actions/composer@v6
        with:
          php_version: "7.2"

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          API_KEY: ${{ vars.API_KEY }}